### ISSUE TITLE
Example of press and hold to change brightness

### ISSUE THREAD

**Issue by SolomonHD** [jay-kub/inovelli-matter-switch-tap-sequences#8]
First, this is an awesome blueprint I was having trouble programming my Inovelli White, I am glad this repo exists.

May I have an example on how to setup press and hold to increase or decrease brightness?

**Comment by jay-kub** [comment]
Hey, thanks. Is this what you're looking for?

```yaml
alias: Example
description: ""
use_blueprint:
  path: jay-kub/inovelli-matter-switch-tap-sequences.yaml
  input:
    entity_up: event.kitchen_table_up
    entity_down: event.kitchen_table_down
    entity_config: event.kitchen_table_config
    entity_light: light.kitchen_table
    target_light: light.kitchen_ceiling
    reverse_sync: true
    min_brightness: 23
```

**Comment by SolomonHD** [comment]
I don't think that's it; I was thinking more along the lines of hold up button and the brightness increases by 15% every 2 seconds.

Also, I would like to hold the config button and cycle through a selection of colors.

**Comment by mjkosin68** [comment]
Hey Solomon, to use the config button to cycle through colors, I set up a counter that would count up every time I hit the config button, then when it hits 12, it resets back down to 1.  Then based on the value of the counter I set the RGBWW color of my light to the appropriate color and drive the color bar on the switch to match.

**Comment by clintandrewhall** [comment]
@SolomonHD I think this is what you want:

```yaml

alias: Example
description: ""
use_blueprint:
  path: jay-kub/inovelli-matter-switch-tap-sequences.yaml
  input:
    entity_up: event.kitchen_table_up
    entity_down: event.kitchen_table_down
    entity_config: event.kitchen_table_config
    entity_light: light.kitchen_table
    target_light: light.kitchen_ceiling
    reverse_sync: true
    upHeld:
      - repeat:
          sequence:
            - action: light.turn_on
              metadata: {}
              data:
                brightness_step_pct: 10
              target:
                entity_id: light.kitchen_ceiling
          until:
            - condition: state
              entity_id: event.kitchen_table_up
              attribute: event_type
              state: long_release
    downHeld:
      - repeat:
          sequence:
            - action: light.turn_on
              metadata: {}
              data:
                brightness_step_pct: -10
              target:
                entity_id: light.kitchen_ceiling
          until:
            - condition: state
              entity_id: event.kitchen_table_down
              attribute: event_type
              state: long_release
```

You can adjust the percentage, as well as add a `transition` of two seconds, (but I've found it's slow enough as it is.
